### ISSUE TITLE
Version 7 throws "No signature of method" error when running android assembleRelease

### ISSUE THREAD

**Issue by matt-dalton** [carnivalmobile/carnival-sdk-react-native#79]
Sicne version 7.0.0 I get the following error:
```* Where:
Build file '/Users/me/projects/app/node_modules/react-native-sailthru-mobile/android/build.gradle' line: 18

* What went wrong:
A problem occurred evaluating project ':react-native-sailthru-mobile'.
> No signature of method: build_bebwb3euhgyt5ylaeyae86.android() is applicable for argument types: (build_bebwb3euhgyt5ylaeyae86$_run_closure1) values: [build_bebwb3euhgyt5ylaeyae86$_run_closure1@3ac7ce]

**Comment by igstewart3** [comment]
I believe this is a result of updating the build tools version, it should be resolved by #82
If you want to work around the error prior to this change, you can either use `buildToolsVersion '30.0.3'` or manually remove the `lint` block from the SDK `build.gradle`

**Comment by igstewart3** [comment]
This issue should be resolved in [v8.0.0](https://github.com/carnivalmobile/carnival-sdk-react-native/releases/tag/v8.0.0), let us know if you notice any further issues here.

**Comment by nikhilameriya** [comment]
Still see the No signature issue with v8.0.0. Please reopen.
